### ISSUE TITLE
Unintentional border-radius on non-inset table-view-list-divider? (2.0)

### ISSUE THREAD

**Issue by yocontra** [twbs/ratchet#233]
![this](https://i.cloudup.com/7NoUECWKEy-2000x2000.png)

Coming from

``` css
.table-view .table-view-divider:first-child {
  top: 0;
  border-radius: 6px 6px 0 0;
}
```

Is this an iOS7 thing or is it unintentional? It seems like this was maybe meant for inset table-view dividers
