### ISSUE TITLE
Support toggles in input-rows (2.0)

### ISSUE THREAD

**Issue by yocontra** [twbs/ratchet#239]
HTML:

``` html
<form class="login input-group">
   <div class="input-row">
      <label>Name</label>
      <input type="text" required="true" placeholder="Name your challenge">
   </div>
   <div class="input-row">
      <label>Duration</label>
      <input type="number" required="true" min="1" max="11" placeholder="Number of weeks">
   </div>
   <div class="input-row">
      <label>Public</label>
      <div class="toggle">
         <div class="toggle-handle"></div>
      </div>
   </div>
</form>
```

Right now it displays like this

![this](https://i.cloudup.com/GR2Gba6dB3-1200x1200.png)

Adding this CSS

``` css
.input-row {
  position: relative;
}

.input-row .toggle {
  position: absolute;
  top: 4px;
  right: 10px;
}
```

Makes it display like this

![this](https://i.cloudup.com/i49e2BFQJJ-1200x1200.png)

Once again hacky CSS to workaround the problem and still unsure about iOS standards on this.
