### ISSUE TITLE
Android tabs padding

### ISSUE THREAD

**Issue by silvenon** [twbs/ratchet#376]
Android theme has tabs on the top, while the base and iOS theme have them on the bottom. The problem is that `.content` is still styled to have bottom padding, rather than top. This is a bit tricky to fix, precedence-wise.

``` scss
// base.scss
// Tab bar padding
.bar-tab ~ .content {
  padding-bottom: $bar-tab-height;
}
```

``` scss
// theme-android.scss
.bar-tab ~ .content {
  padding-bottom: $bar-tab-height;
}
```

The latter should be:

``` scss
// theme-android.scss
.bar-tab ~ .content {
  padding-top: $bar-tab-height;
  padding-bottom: 0;
}
```

But then these would get overwritten:

``` scss
// base.scss
// Footer bar padding
.bar-footer ~ .content {
  padding-bottom: $bar-base-height;
}
.bar-footer-secondary ~ .content {
  padding-bottom: ($bar-base-height*2);
}
```

Seems like some style duplication is in order?
