### ISSUE TITLE
docs.css issue

### ISSUE THREAD

**Issue by XhmikosR** [twbs/ratchet#390]
When [this](https://github.com/twbs/ratchet/blob/master/sass/theme-ios.scss#L588) is included [here](https://github.com/twbs/ratchet/blob/master/sass/docs.scss#L1143) it results in the following:

``` css
.platform-ios {
  @-webkit-keyframes fadeOverlay {
    from {
      -webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0), -320px 0 0 rgba(0, 0, 0, 0);
      box-shadow: 0 0 10px rgba(0, 0, 0, 0), -320px 0 0 rgba(0, 0, 0, 0);
    }

    to {
      -webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0.3), -320px 0 0 rgba(0, 0, 0, 0.1);
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3), -320px 0 0 rgba(0, 0, 0, 0.1);
    }
}
```

This isn't valid CSS and it breaks many tools like clean-css.

/CC @connor @connors
