### ISSUE TITLE
Feature Request - Label -> Value pattern within Table views

### ISSUE THREAD

**Issue by Schmalzy** [twbs/ratchet#565]
In iOS and Android settings menus, there is often a Label -> Value design pattern within Table-views.

iOS Example:
![screen shot 2014-04-18 at 3 34 42 pm](https://cloud.githubusercontent.com/assets/1474152/2745641/eecd13b4-c738-11e3-8356-a59e21bb10fd.png)

I could not find built-in classes for the "Value" part of this pattern, and wanted to propose it be added.

Below are examples of both iOS and Android that I came up with.

``` HTML
<ul class="table-view">
     <li class="table-view-cell">Label <span class="label-value">Value</span></li>
</ul>
```

The iOS version uses the same CSS used to position .btn, .badge and .toggle elements inline and to the right, within a table-view-cell. 

``` CSS
.table-view-cell > .label-value{
    position: absolute;
    top: 50%;
    right: 15px;
    -webkit-transform: translateY(-50%);
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
    color: #8f8f94;
}
```

The Android version would drop the "Value" below the "Label" which is more inline with the Android style guide.

``` CSS
.table-view-cell > .label-value {
    display: block;
    color: #929292;
    font-size: 14px;
    line-height: 18px;
}
```

iOS Demo:
![screen shot 2014-04-18 at 3 16 16 pm](https://cloud.githubusercontent.com/assets/1474152/2745682/9c2ecf70-c739-11e3-852f-a05bba1dc074.png)
Android Demo:
![screen shot 2014-04-18 at 3 15 04 pm](https://cloud.githubusercontent.com/assets/1474152/2745684/9fcf014a-c739-11e3-8208-4e8edc01744c.png)
